"""catalogo e instituciones

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-11 12:25:40.403227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorias')),
    sa.UniqueConstraint('nombre', name=op.f('uq_categorias_nombre'))
    )
    op.create_table('instituciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('tipo', sa.Enum('secretaria_estado', 'institucion_descentralizada', 'ente_regulador', 'empresa_publica', 'municipalidad', 'poder_judicial', 'organo_control', 'empresa_privada', 'otro', name='tipo_institucion'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instituciones')),
    sa.UniqueConstraint('nombre', name=op.f('uq_instituciones_nombre'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instituciones')
    op.drop_table('categorias')
    # ### end Alembic commands ###
    # Eliminar el tipo de enum explícitamente o el siguiente upgrade falla con "type already exists".
    sa.Enum(name='tipo_institucion').drop(op.get_bind(), checkfirst=True)
