"""tabla denuncias

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-11 17:19:23.215962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('denuncias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_hash', sa.String(length=255), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.Column('nivel_identidad', sa.Enum('anonimo', 'seudonimo', 'publico', name='nivel_identidad'), nullable=False),
    sa.Column('gravedad', sa.Enum('baja', 'media', 'alta', 'critica', name='gravedad'), nullable=True),
    sa.Column('estado', sa.Enum('recibida', 'en_saneamiento', 'en_triaje', 'en_revision_doble', 'escalada', 'en_redaccion', 'critica', 'derivada', 'publicada', 'rechazada', name='estado_denuncia'), nullable=False),
    sa.Column('relato', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name=op.f('fk_denuncias_categoria_id_categorias'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], name=op.f('fk_denuncias_institucion_id_instituciones'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_denuncias')),
    sa.UniqueConstraint('codigo_hash', name=op.f('uq_denuncias_codigo_hash'))
    )
    op.create_index('ix_denuncias_categoria_institucion', 'denuncias', ['categoria_id', 'institucion_id'], unique=False)
    op.create_index('ix_denuncias_estado', 'denuncias', ['estado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_denuncias_estado', table_name='denuncias')
    op.drop_index('ix_denuncias_categoria_institucion', table_name='denuncias')
    op.drop_table('denuncias')
    # ### end Alembic commands ###
    sa.Enum(name='estado_denuncia').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='gravedad').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='nivel_identidad').drop(op.get_bind(), checkfirst=True)