"""evidencias y mensajes

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-11 18:15:21.547326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denuncia_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('mime', sa.String(length=120), nullable=False),
    sa.Column('sanitizada', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['denuncia_id'], ['denuncias.id'], name=op.f('fk_evidencias_denuncia_id_denuncias'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidencias'))
    )
    op.create_index('ix_evidencias_denuncia', 'evidencias', ['denuncia_id'], unique=False)
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denuncia_id', sa.Integer(), nullable=False),
    sa.Column('autor', sa.Enum('denunciante', 'revisor', name='autor_mensaje'), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['denuncia_id'], ['denuncias.id'], name=op.f('fk_mensajes_denuncia_id_denuncias'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mensajes'))
    )
    op.create_index('ix_mensajes_denuncia_creado', 'mensajes', ['denuncia_id', 'creado_en'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mensajes_denuncia_creado', table_name='mensajes')
    op.drop_table('mensajes')
    op.drop_index('ix_evidencias_denuncia', table_name='evidencias')
    op.drop_table('evidencias')
    # ### end Alembic commands ###
    sa.Enum(name='autor_mensaje').drop(op.get_bind(), checkfirst=True)