"""revisores asignaciones y revisiones

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-12 09:12:12.215870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revisores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('organizacion', sa.String(length=160), nullable=False),
    sa.Column('rol', sa.Enum('revisor', 'supervisor', name='rol_revisor'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revisores'))
    )
    op.create_table('asignaciones_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denuncia_id', sa.Integer(), nullable=False),
    sa.Column('revisor_id', sa.Integer(), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['denuncia_id'], ['denuncias.id'], name=op.f('fk_asignaciones_revision_denuncia_id_denuncias'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revisor_id'], ['revisores.id'], name=op.f('fk_asignaciones_revision_revisor_id_revisores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asignaciones_revision')),
    sa.UniqueConstraint('denuncia_id', 'revisor_id', name='uq_asignacion_denuncia_revisor')
    )
    op.create_index('ix_asignaciones_revisor_pendiente', 'asignaciones_revision', ['revisor_id', 'completada'], unique=False)
    op.create_table('revisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denuncia_id', sa.Integer(), nullable=False),
    sa.Column('revisor_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('procede', 'rechaza', 'solicita_ampliacion', 'deriva', name='decision_revision'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['denuncia_id'], ['denuncias.id'], name=op.f('fk_revisiones_denuncia_id_denuncias'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revisor_id'], ['revisores.id'], name=op.f('fk_revisiones_revisor_id_revisores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revisiones'))
    )
    op.create_index('ix_revisiones_denuncia', 'revisiones', ['denuncia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_revisiones_denuncia', table_name='revisiones')
    op.drop_table('revisiones')
    op.drop_index('ix_asignaciones_revisor_pendiente', table_name='asignaciones_revision')
    op.drop_table('asignaciones_revision')
    op.drop_table('revisores')
    # ### end Alembic commands ###
    sa.Enum(name='decision_revision').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='rol_revisor').drop(op.get_bind(), checkfirst=True)
    