"""publicaciones y derivaciones

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-12 10:35:47.340179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('derivaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denuncia_id', sa.Integer(), nullable=False),
    sa.Column('autoridad', sa.String(length=160), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['denuncia_id'], ['denuncias.id'], name=op.f('fk_derivaciones_denuncia_id_denuncias'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_derivaciones'))
    )
    op.create_index('ix_derivaciones_denuncia', 'derivaciones', ['denuncia_id'], unique=False)
    op.create_table('publicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denuncia_id', sa.Integer(), nullable=False),
    sa.Column('texto_redactado', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['denuncia_id'], ['denuncias.id'], name=op.f('fk_publicaciones_denuncia_id_denuncias'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publicaciones')),
    sa.UniqueConstraint('denuncia_id', name=op.f('uq_publicaciones_denuncia_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicaciones')
    op.drop_index('ix_derivaciones_denuncia', table_name='derivaciones')
    op.drop_table('derivaciones')
    # ### end Alembic commands ###
