"""bitacora y descargas de evidencia

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-12 13:08:36.284966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitacora',
    sa.Column('indice', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hash_anterior', sa.CHAR(length=64), nullable=True),
    sa.Column('hash_actual', sa.CHAR(length=64), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('indice', name=op.f('pk_bitacora')),
    sa.UniqueConstraint('hash_actual', name=op.f('uq_bitacora_hash_actual'))
    )
    op.create_index('ix_bitacora_creado', 'bitacora', ['creado_en'], unique=False)
    op.create_index('ix_bitacora_tipo_evento', 'bitacora', ['tipo_evento'], unique=False)
    op.create_table('descargas_evidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidencia_id', sa.Integer(), nullable=False),
    sa.Column('revisor_id', sa.Integer(), nullable=False),
    sa.Column('justificacion', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidencia_id'], ['revisores.id'], name=op.f('fk_descargas_evidencia_evidencia_id_revisores'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revisor_id'], ['revisores.id'], name=op.f('fk_descargas_evidencia_revisor_id_revisores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_descargas_evidencia'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('descargas_evidencia')
    op.drop_index('ix_bitacora_tipo_evento', table_name='bitacora')
    op.drop_index('ix_bitacora_creado', table_name='bitacora')
    op.drop_table('bitacora')
    # ### end Alembic commands ###
