"""credenciales y sesiones de revisor

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-10 09:00:30.003354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: Union[str, None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sesiones_revisor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revisor_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['revisor_id'], ['revisores.id'], name=op.f('fk_sesiones_revisor_revisor_id_revisores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sesiones_revisor')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sesiones_revisor_token_hash'))
    )
    op.create_index('ix_sesiones_revisor', 'sesiones_revisor', ['revisor_id'], unique=False)
    op.add_column('revisores', sa.Column('usuario', sa.String(length=60), nullable=False))
    op.add_column('revisores', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.create_unique_constraint(op.f('uq_revisores_usuario'), 'revisores', ['usuario'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_revisores_usuario'), 'revisores', type_='unique')
    op.drop_column('revisores', 'password_hash')
    op.drop_column('revisores', 'usuario')
    op.drop_index('ix_sesiones_revisor', table_name='sesiones_revisor')
    op.drop_table('sesiones_revisor')
    # ### end Alembic commands ###
