"""corregir descargas_evidencia

Revision ID: 0013
Revises: 0012
Create Date: 2026-09-10 09:44:39.479365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0013'
down_revision: Union[str, None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('descargas_evidencia', sa.Column('marca_id', sa.UUID(), nullable=False))
    op.add_column('descargas_evidencia', sa.Column('sha256_copia', sa.CHAR(length=64), nullable=False))
    op.create_index('ix_descargas_evidencia_id', 'descargas_evidencia', ['evidencia_id'], unique=False)
    op.create_index('ix_descargas_revisor', 'descargas_evidencia', ['revisor_id'], unique=False)
    op.create_unique_constraint(op.f('uq_descargas_evidencia_marca_id'), 'descargas_evidencia', ['marca_id'])
    op.drop_constraint('fk_descargas_evidencia_evidencia_id_revisores', 'descargas_evidencia', type_='foreignkey')
    op.create_foreign_key(op.f('fk_descargas_evidencia_evidencia_id_evidencias'), 'descargas_evidencia', 'evidencias', ['evidencia_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_descargas_evidencia_evidencia_id_evidencias'), 'descargas_evidencia', type_='foreignkey')
    op.create_foreign_key('fk_descargas_evidencia_evidencia_id_revisores', 'descargas_evidencia', 'revisores', ['evidencia_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('uq_descargas_evidencia_marca_id'), 'descargas_evidencia', type_='unique')
    op.drop_index('ix_descargas_revisor', table_name='descargas_evidencia')
    op.drop_index('ix_descargas_evidencia_id', table_name='descargas_evidencia')
    op.drop_column('descargas_evidencia', 'sha256_copia')
    op.drop_column('descargas_evidencia', 'marca_id')
    # ### end Alembic commands ###
